### ISSUE TITLE
[Refactor] SignupViewController 리팩토링

### ISSUE THREAD

**Issue by Rama-Moon** [Team-Recordy/Recordy-iOS#133]
## 🛠 Issue
스프린트 과정에서 변동이 적을 것으로 예상되는 SignupViewController를 리팩토링합니다.

## 📝 To-do
- [ ] 다음 버튼을 눌렀을 때 View를 교체하는 함수 수정
- [ ] 다음 버튼을 눌렀을 때 NavigationController Title 변경
- [ ] SignupViewController에서 ViewController와 View를 분리

**Comment by sebbbin** [comment]
굿 좋아요 !

**Comment by Rama-Moon** [comment]
thx🫡
