### ISSUE TITLE
[Feat] 검색 뷰 기능 구현

### ISSUE THREAD

**Issue by Rama-Moon** [Team-Recordy/Recordy-iOS#172]
## 🛠 Issue
검색 뷰 기능, 디테일을 구현합니다.

## 📝 To-do
- [x] 검색 뷰 들어가자 마자 키보드 나오게
- [ ] MockData를 이용해서 검색 기능 구현
- [ ] 장소, 전시회 각각 검색 되도록
- [x] 키보드에 완료버튼 디테일
