### ISSUE TITLE
[Feat] ChipButton Component 구현

### ISSUE THREAD

**Issue by 0gonge** [Team-Recordy/Recordy-iOS#20]
## 🛠 Issue
- 버튼 컴포넌트 나머지들(ex.chip)을 제작해 줍니다. 

## 📝 To-do
- [x] chipKeyWordButton컴포넌트 제작
- [x] followButton 컴포넌트 제작
- [x]  smallChipButton 컴포넌트 제작
- [x] mediumButton 컴포넌트 제작
