### ISSUE TITLE
[Feat] Signup 뷰 함수 구현

### ISSUE THREAD

**Issue by Rama-Moon** [Team-Recordy/Recordy-iOS#53]
## 🛠 Issue
SignUp 뷰에서 필요한 함수를 구현합니다.

## 📝 To-do
- [ ] SignupViewController에 ProgressView 컴포넌트 추가
- [ ] TermsView에서 토글 버튼을 눌렀을 때 버튼 상태 변경
- [ ] TermsView에서 모든 토글 버튼을 누르면 다음 버튼 활성화
- [ ] NicknameTextField 정규식 적용
- [ ] 닉네임 작성 조건에 따른 NicknameTextField 상태 변경, 다음 버튼 활성화
